services:
  nifi:
    image: apache/nifi:2.0.0.M4
    container_name: nifi
    hostname: nifi
    ports:
      - '8443:8443'
    deploy:
      resources:
        limits:
          cpus: '4'  # Limita o uso de CPU
          memory: 3G  # Limita o uso de memória
        reservations:
          cpus: '2'  # Reserva pelo menos
          memory: 2G  # Reserva pelo menos
    volumes:
#      - ./jar:/opt/jdbc
#      - ./nifi/logs:/opt/nifi/nifi-current/logs/
      - ./metastore/hive-site.xml:/opt/nifi/nifi-current/core-site.xml
      - ./nifi/properties:/opt/nifi/nifi-current/properties  #credentials.properties (minio)
#      - ./nifi/db/database_repository:/opt/nifi/nifi-current/database_repository
#      - ./nifi/db/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
#      - ./nifi/db/content_repository:/opt/nifi/nifi-current/content_repository
#      - ./nifi/db/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: 123456789012
    networks:
      - network



  postgres:
    image: 'postgres:latest'
    hostname: postgres
    container_name: postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    networks:
      - network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - network
      
  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: |
      sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 minio minio123 &&
      mc mb myminio/landing &&
      mc mb myminio/bronze &&
      mc mb myminio/silver &&
      mc mb myminio/gold &&
      mc mb myminio/warehouse &&
      mc policy set public myminio/warehouse
      "
    networks:
      - network


  hive-metastore:
    image: 'custom-hive:3.1.3'
    hostname: hive-metastore
    container_name: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./metastore/hive-site.xml:/opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml:ro
    environment:
#      - SERVICE_NAME=metastore
#      - HIVE_METASTORE_RUN=1
#      - HIVE_METASTORE_DB_TYPE=derby
#      - HIVE_DB_PATH=/metastore_db
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - DB_HOST=postgres                 # Nome do serviço PostgreSQL (deve corresponder ao nome do serviço abaixo)
      - DB_PORT=5432                     # Porta padrão do PostgreSQL
      - DB_NAME=hive_db                  # Nome do banco de dados no PostgreSQL
      - DB_USER=admin                    # Usuário do banco de dados PostgreSQL
      - DB_PASS=admin                    # Senha do banco de dados PostgreSQL
    depends_on:
      - minio-mc
      - postgres
    networks:
      - network

  trino:
    image: 'trinodb/trino:410'
    hostname: trino
    container_name: trino
    ports:
      - '8080:8080'
    volumes:
      - ./trino/etc:/etc/trino/:ro
      - ./trino/conf/core-hive.xml:/usr/lib/trino/plugin/hive/core-site.xml
      - ./jar/postgresql-42.7.4.jar:/usr/lib/trino/plugin/hive/postgresql-42.7.4.jar
#      - ./jar/aws-java-sdk-bundle-1.12.367.jar:/usr/lib/trino/plugin/hive/aws-java-sdk-bundle-1.12.367.jar
    depends_on:
      - minio-mc
      - hive-metastore
    networks:
      - network

volumes:
  minio-data:
    driver: local

networks:
  network:
    name: network
    driver: bridge

